apiVersion: v1
kind: Namespace
metadata:
  name: vigil
  labels:
    app.kubernetes.io/name: vigil
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

