apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigil-backend-worker
  annotations:
    iam.gke.io/gcp-service-account: __WORKER_SERVICE_ACCOUNT__
    iam.gke.io/return-principal-id-as-email: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigil-scheduler
  annotations:
    iam.gke.io/gcp-service-account: __SCHEDULER_SERVICE_ACCOUNT__
    iam.gke.io/return-principal-id-as-email: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigil-recorder
  annotations:
    iam.gke.io/gcp-service-account: __RECORDER_SERVICE_ACCOUNT__
    iam.gke.io/return-principal-id-as-email: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigil-synthetic-hls
automountServiceAccountToken: false

