apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: vigil
      app.kubernetes.io/managed-by: kustomize
      vigil.dev/environment: demo

